const dailyQuestions = [
  "Qual foi a primeira impressão que tiveste de mim?",
  "Qual é o teu encontro de sonho que ainda não realizámos?",
  "Se pudesses descrever a nossa relação numa palavra hoje, qual seria?",
  "O que é que eu fiz recentemente que te fez sentir muito amado(a)?",
  "Qual é a música que mais te faz lembrar de nós?",
  "Se fôssemos viajar amanhã para qualquer lugar do mundo, para onde iríamos?",
  "Qual foi a melhor gargalhada que demos juntos?",
  "Qual é a característica ou hábito que mais admiras em mim?",
  "O que é que mais valorizas no tempo que passamos juntos?",
  "Se pudesses planear o dia perfeito para nós dois, como seria?",
  "Qual é a vossa memória favorita de quando começámos a namorar?",
  "Que pequeno gesto meu te faz sentir especial no dia a dia?",
  "Se tivesses de escolher um filme ou livro que representa o nosso amor, qual seria?",
  "O que é que gostavas de aprender a fazer comigo no futuro?",
  "Qual é o teu maior sonho pessoal que queres que eu te ajude a realizar?",
  "Onde te vês connosco daqui a cinco anos?",
  "Qual é a comida que associas imediatamente a nós os dois?",
  "Qual foi o momento em que percebeste que estavas apaixonado(a) por mim?",
  "Se pudéssemos adotar qualquer animal de estimação (real ou fictício), qual seria?",
  "Qual é a alcunha fofa que eu te dou que mais gostas?",
  "Se tivesses de me descrever a um desconhecido, o que dirias?",
  "Qual é a viagem mais especial que já fizemos juntos e porquê?",
  "O que é que te faz sentir mais seguro(a) na nossa relação?",
  "Se fosses fazer-me uma surpresa hoje (sem restrições de orçamento), o que seria?",
  "Qual é a foto nossa que mais gostas e que recordação te traz?",
  "Que piada privada nossa te faz sempre rir, não importa quando?",
  "Se pudesses mudar temporariamente de vida connosco por uma semana, para onde iríamos?",
  "Qual é o segredo para mantermos a nossa cumplicidade tão forte?",
  "Como é que gostas de ser mimado(a) quando estás num dia mau?",
  "Qual é a primeira coisa em que pensas quando acordas e me vês ao teu lado?",
  "Se a nossa história de amor fosse um sabor de gelado, que sabor seria?",
  "Qual é o momento do dia em que mais sentes a minha falta?",
  "Qual é o teu maior orgulho em ver-nos crescer como casal?",
  "O que é que te faz sorrir quando pensas no nosso futuro juntos?",
  "Se pudéssemos ter um superpoder partilhado, qual escolherias para nós?"
];

module.exports = dailyQuestions;
